version: "3"
services:
  app:
    image: jc21/nginx-proxy-manager:latest
    container_name: nginx-proxy-manager
    environment:
      DB_MYSQL_HOST: 'db'
      DB_MYSQL_PORT: 3306
      DB_MYSQL_USER: 'npm'
      DB_MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      DB_MYSQL_NAME: 'npm'
    volumes:
      - /home/pi/docker-proj/nginx-proxy-manager/config.json:/app/config/production.json
      - /home/pi/docker-proj/nginx-proxy-manager/data:/data
      - /home/pi/docker-proj/nginx-proxy-manager/letsencrypt:/etc/letsencrypt
    depends_on:
      - db
    ports:
      - 80:80
      - 443:443
      - 81:81
    restart: unless-stopped
  db:
    image: linuxserver/mariadb:latest
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: npm
      MYSQL_USER: npm
      MYSQL_PASSWORD: ${DATABASE_PASSWORD}
      PUID: ${USER_UID}
      PGID: ${USER_GID}
      TZ: ${TZ}

    volumes:
      - /home/pi/docker-proj/nginx-proxy-manager/database:/config
